<?php

/**
 * @file
 * Code for the Rettet indhold feature.
 */
include_once 'rettet_indhold.features.inc';

/**
 * Implements hook_action_info().
 */
function rettet_indhold_admin() {
  $form = array();

  $form['rettet_indhold_mail_to'] = array(
    '#type' => 'textfield',
    '#title' => t('Email of recipient'),
    '#default_value' => variable_get('rettet_indhold_mail_to', 'bymedl@ishoj.dk'),
    '#size' => 100,
    '#maxlength' => 512,
    '#description' => t("Email of recipient."),
    '#required' => TRUE,
  );

  $form['rettet_indhold__mail_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Email subject'),
    '#default_value' => variable_get('rettet_indhold__mail_subject', 'Updated nodes info'),
    '#size' => 100,
    '#maxlength' => 512,
    '#description' => t("Email subject."),
    '#required' => TRUE,
  );

  $form['rettet_indhold__mail_body'] = array(
    '#type' => 'textarea',
    '#title' => t('Email body'),
    '#default_value' => variable_get('rettet_indhold__mail_body', 'The last updated node list is attached below.'),
    '#rows' => 10,
    '#cols' => 40,
    '#resizable' => TRUE,
    '#description' => t("Email body."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function rettet_indhold_menu() {

  $items = array();

  $items['admin/settings/rettet_indhold'] = array(
    'title' => 'Rettet indhold settings',
    'description' => 'Description of your On this date settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rettet_indhold_admin'),
    'access arguments' => array('administer onthisdate settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['rettet_indhold/%'] = array(
    'title' => 'Rettet indhold process',
    'description' => 'Rettet indhold process page',
    'page callback' => 'rettet_indhold_send_notification',
    'page arguments' => array(1),
    'access arguments' => array('access content'));
  return $items;
}

function rettet_indhold_send_notification($input) {

  $mail_to = variable_get("rettet_indhold_mail_to", 'bymedl@ishoj.dk');
  $mail_subject = variable_get("rettet_indhold__mail_subject", 'Updated nodes info');
  $mail_body = variable_get("rettet_indhold__mail_body", 'The last updated node list is attached below.');

  $node_ids = explode(',', $input);
  $mail_body_bottom = NULL;
  if (count($node_ids) > 0) {
    $nodes = node_load_multiple($node_ids);
    foreach ($nodes as $node) {
      $node_path = drupal_get_path_alias('/node/' . (int) $node->nid);

      $alias = drupal_get_path_alias($path);
      $mail_body_bottom .= '<a href="' . $node_path . '" target="_blank" >' . $node->title . '</a><br>';
    }
  }
  $mail_body = $mail_body . '<br><br>' . $mail_body_bottom;

  // Send the email.
  $params = array(
    'subject' => $mail_subject,
    'body' => $mail_body,
  );
  drupal_mail('rettet_indhold', 'rettet_indhold', $mail_to, language_default(), $params);

  return t('Mail send to %mail_to', array('%mail_to' => $mail_to));
}

/**
 * Implements hook_mail for rettet_indhold.
 */
function rettet_indhold_mail($key, &$message, $params) {
  switch ($key) {
    case 'rettet_indhold':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}
